# Generated by Django 5.0.6 on 2024-06-06 17:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agendamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DiasDaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segunda', models.CharField(max_length=50)),
                ('terca', models.CharField(max_length=50)),
                ('quarta', models.CharField(max_length=50)),
                ('quinta', models.CharField(max_length=50)),
                ('sexta', models.CharField(max_length=50)),
                ('sabado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manhaA', models.CharField(max_length=50)),
                ('manhaB', models.CharField(max_length=50)),
                ('tardeA', models.CharField(max_length=50)),
                ('tardeB', models.CharField(max_length=50)),
                ('noiteA', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=50)),
                ('equipamentos', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('idade', models.IntegerField()),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('quartos', models.CharField(max_length=50)),
            ],
        ),
    ]
